server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        a2u_event:
          destination: a2u_link_event
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 50
        debug_event_name:
          destination: debug_event
          producer:
            partition-key-expression: headers['partitionKey']
            partition-count: 50
      kafka:
        binder:
          auto-add-partitions: true
          replication-factor: 1

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9094

  data:
    r2dbc:
      repositories:
      enabled: true


  r2dbc:
    url: r2dbc:postgresql://localhost:15432/ledger-accounting
    pool:
      enabled: true
      initial-size: 10
    username: postgres

  liquibase:
    url: jdbc:postgresql://localhost:15432/ledger-accounting
    user: postgres
  datasource:
    url: jdbc:postgresql://localhost:15432/ledger-accounting
    username: postgres

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9494/auth/realms/t1
          jwk-set-uri: http://localhost:9494/auth/realms/t1/protocol/openid-connect/certs
